version: "3.6"
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5427:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    environment:
      - REDIS_REPLICATION_MODE=master
    command: redis-server --save 60 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    restart: always
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./init/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./init/definitions.json:/etc/rabbitmq/definitions.json:ro
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
      - rabbitmq
    ports:
      - "80:80"
    environment:
      SERVER_HOST: "http://localhost"
      SERVER_PORT: 80
      JWT_SECRET: "046d73e1-027f-4a28-8e9c-fa696f9e4005"
      REQUEST_LIMIT: 100
      CACHE_TTL_SEC: 5
      RATE_LIMIT_PER_SEC: 5
      MAIL_TRANSPORT: "smtp://nick.zakonov@gmail.com:123456@smtp.gmail.com"
      MAIL_FROM: "nick.zakonov@gmail.com"
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "postgres"
      DATABASE_NAME: "postgres"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
volumes:
  db_data:
  redis:
  rabbitmq_data:
